package: pdfout
version: '10.0.2'
pdfjs: '5.4.394'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.15.1'
    php:
        version: '>=8.1'
        extensions: [gd]

page:
    title: 'translate:title'
    perm: pdfout[]
    icon: rex-icon fa-file-pdf-o
    subpages:
        overview: 
            title: 'translate:pdfout_overview'
            perm: pdfout[]
        config: 
            title: 'translate:pdfout_config'
            perm: pdfout[config]
        demo: 
            title: 'translate:pdfout_demo'
            perm: pdfout[demo]
        certificates: 
            title: 'translate:pdfout_certificates'
            perm: pdfout[certificates]
        docs:  
             { title: 'translate:pdfout_docs',  icon: "rex-icon fa-question-circle", subPath: README.md}
        api:  
             { title: 'API Referenz',  icon: "rex-icon fa-code", subPath: API.md}
        bestpractices:  
             { title: 'Best Practices',  icon: "rex-icon fa-lightbulb-o", subPath: BEST_PRACTICES.md} 
