# Alle hier gesetzten Werte können über $addon->getProperty($key) abgefragt werden

package: pdfout
version: '1.5.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.3.0'
