package: pdfout
version: '1.7.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.8.0'
    php:
        version: '^7.1'
        extensions: [gd]