package: pdfout
version: '2.0.0-dev'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.8.0'
    php:
        version: '^7.1'
        extensions: [gd]