package: pdfout
version: '7.0.0-dev'
vendor: 'v2.0.1'
pdfjs: 'v2.16.105'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.14.0'
    php:
        version: '>=8.0'
        extensions: [gd]
