package: pdfout
version: '8.1.3'
vendor: '2.0.8'
pdfjs: '4.0.269'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.15.1'
    php:
        version: '>=8.1'
        extensions: [gd]
