package: pdfout
version: '8.4.0'
vendor: '3.0.0'
pdfjs: '4.6.82'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.15.1'
    php:
        version: '>=8.1'
        extensions: [gd]
