package: pdfout
version: '6.2.1'
vendor: 'v2.0.1'
pdfjs: 'v2.16.105'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.13.0'
    php:
        version: '>=7.4'
        extensions: [gd]
