package: pdfout
version: '5.2.0'
vendor: 'v1.2.1'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.10.0'
    php:
        version: '>=7.4'
        extensions: [gd]
