package: pdfout
version: '8.3.0'
vendor: '3.0.0'
pdfjs: 'v4.2.67'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.15.1'
    php:
        version: '>=8.1'
        extensions: [gd]
