package: pdfout
version: '4.1.1'
vendor: 'v1.1.0'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.8.0'
    php:
        version: '>=7.1'
        extensions: [gd]

page:
    title: translate:pdfout
    icon: fa-icon rex-icon fa-file-pdf-o
    perm: admin[]
    subpages:
        help:
            title: translate:pdfout_docs
            subPath: README.md
            perm: admin[]
