package: pdfout
version: '7.0.4'
vendor: 'v2.0.1'
pdfjs: 'v3.2.146'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.14.0'
    php:
        version: '>=8.0'
        extensions: [gd]
