package: pdfout
version: '8.0.1'
vendor: '2.0.3'
pdfjs: 'v3.10.111'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.14.0'
    php:
        version: '>=8.0'
        extensions: [gd]
