package: pdfout
version: '2.1.1-dev'
vendor: '0.8.5'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.8.0'
    php:
        version: '^7.1'
        extensions: [gd]
