package: pdfout
version: '7.1.4'
vendor: '2.0.3'
pdfjs: 'v3.3.122'
author: Friends Of REDAXO
supportpage: https://github.com/FriendsOfREDAXO/pdfout
requires:
    redaxo: '^5.14.0'
    php:
        version: '>=8.0'
        extensions: [gd]
